//package exceptionExample;
//
//public class MainClass {
//    static void main(String[] args) {
//
//
//        int[] arr = new int[5];
//
//        try{
////            getNumber(arr);
//        }catch (Exception e){
//            System.out.println(e.getMessage());
//        }
//
//
////        try{
//////            int a = 10/0;
////            System.out.println(arr[10]);
////            System.out.println("hello Ji");
////        } catch (Exception e){
////            System.out.println(e.getMessage());
////        } finally {
////            System.out.println("This is finally block");
////        }
//
//
//    }
//    public static int getNumber throw ArrayIndexOutOfBoundsException(int a[]){
//        return a[8];
//    }
//}
//
